### ISSUE TITLE
Add non-www switch

### ISSUE THREAD

**Issue by szepeviktor** [ScholliYT/Broken-Links-Crawler-Action#19]
While checking a www website manually I've noticed there are non-www (broken?) linkst.

```yaml
  website_url: 'https://github.com/ScholliYT/Broken-Links-Crawler-Action'
  include_url_prefix: 'https://github.com/ScholliYT/Broken-Links-Crawler-Action'
  resolve_before_filtering: 'true'
```

Please consider adding a www switch that includes/follows non-www links.

**Comment by szepeviktor** [comment]
And maybe the reverse

```yaml
  website_url: 'https://website.test'
  include_url_prefix: 'https://website.test'
  resolve_before_filtering: 'true'
```

that includes/follows www links.

**Comment by ScholliYT** [comment]
Are you talking about following links like `https://www.website.test` given the following config:

```yaml
  website_url: 'https://website.test'
  include_url_prefix: 'https://website.test'
  resolve_before_filtering: 'true'
  auto_follow_www: 'true'
```

Can you maybe add a real website where the Issue exists? That would be very helpful.
